# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-22 16:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designMatchApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='administrador',
            name='url_empresa',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
